export const artCategories = [
  {
    title: "Classical & Western Styles",
    items: [
      "Cave Painting",
      "Egyptian Art",
      "Greek Art",
      "Roman Art",
      "Byzantine Art",
      "Gothic Art",
      "Renaissance",
      "Mannerism",
      "Baroque",
      "Rococo",
      "Neoclassicism",
      "Romanticism",
      "Realism",
    ],
  },
  {
    title: "Modern & Contemporary",
    items: [
      "Impressionism",
      "Post-Impressionism",
      "Expressionism",
      "Fauvism",
      "Cubism",
      "Futurism",
      "Dadaism",
      "Surrealism",
      "Abstract Art",
      "Abstract Expressionism",
      "Minimalism",
      "Pop Art",
      "Op Art",
      "Conceptual Art",
      "Contemporary Art",
    ],
  },
  {
    title: "Asian Painting Styles",
    items: [
      "Indian Miniature",
      "Madhubani",
      "Warli",
      "Tanjore",
      "Pattachitra",
      "Kalamkari",
      "Mughal",
      "Chinese Ink",
      "Japanese Sumi-e",
      "Ukiyo-e",
      "Korean Minhwa",
      "Tibetan Thangka",
    ],
  },
  {
    title: "Global & Regional",
    items: [
      "Persian Miniature",
      "Islamic Miniature",
      "Arabic Calligraphy",
      "Ottoman Art",
      "African Tribal",
      "Aboriginal Art",
      "San Rock Art",
      "Russian Icon",
      "Folk Art",
      "Naïve Art",
    ],
  },
  {
    title: "Techniques & Mediums",
    items: [
      "Oil Painting",
      "Watercolor",
      "Acrylic",
      "Fresco",
      "Ink Wash",
      "Mixed Media",
    ],
  },
];
